FROM 		openjdk:8-jdk-alpine
WORKDIR 	/app/
COPY 		target/sidebyside-sboot-hello-demo-1.0-SNAPSHOT.jar .
EXPOSE 		8080
ENTRYPOINT 	["java","-Xmx32M", "-Xms32m","-jar","sidebyside-sboot-hello-demo-1.0-SNAPSHOT.jar"]